;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2019/6/13 10:26:26

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1000=operation intro.html	; ³¬µÍÎÂERP²Ù×÷ÊÖ²áË÷Òý
